#!/usr/bin/env python3
"""
After PyInstaller, split dist output into runtime / pdf / photo / meeting trees for modular installers.

Sizes are uncompressed on-disk totals (approximate installed footprint). Classification uses
path heuristics: optional meeting/photo/pdf add-ons; everything else stays in runtime (shell + shared deps).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

_COMPONENT_ORDER: tuple[str, ...] = ("runtime", "pdf", "photo", "meeting")

# Paths (relative, posix, lower) matching add-on only — order in classify_component matters.
_PHOTO_MARKERS: tuple[str, ...] = (
    "onnxruntime",
    "onnxruntime-",
    "/rembg/",
    "\\rembg\\",
    "pymatting",
    "/skimage/",
    "\\skimage\\",
    "/sklearn/",
    "\\sklearn\\",
    "/cv2/",
    "\\cv2\\",
    "/numba/",
    "\\numba\\",
    "/llvmlite/",
    "\\llvmlite\\",
    "/pooch/",
    "\\pooch\\",
    "/imageio/",
    "\\imageio\\",
    "u2net_human_seg",
    "u2net.onnx",
    "rembg_models",
    "pdfgui/photo/",
    "pdfgui\\photo\\",
)

_MEETING_MARKERS: tuple[str, ...] = (
    "/sounddevice/",
    "\\sounddevice\\",
    "_sounddevice",
    "/vosk/",
    "\\vosk\\",
    "vosk.",  # e.g. speech_recognition/recognizers/vosk.py
    "libvosk",
    "vosk_models",
    "pocketsphinx",
    "/flac-",
    "\\flac-",
    "flac-linux",
)

_PDF_MARKERS: tuple[str, ...] = (
    "pymupdf",
    "/pymupdf/",
    "\\pymupdf\\",
    "libmupdf",
    "/libmupdf",
    "\\libmupdf\\",
    "pdfgui/pdf/",
    "pdfgui\\pdf\\",
    "/fitz/",
    "\\fitz\\",
)


def _norm_rel(p: Path, base: Path) -> str:
    return p.relative_to(base).as_posix().lower()


def classify_component(rel_posix_lower: str) -> str:
    for m in _MEETING_MARKERS:
        if m in rel_posix_lower:
            return "meeting"
    for m in _PHOTO_MARKERS:
        if m in rel_posix_lower:
            return "photo"
    for m in _PDF_MARKERS:
        if m in rel_posix_lower:
            return "pdf"
    return "runtime"


def _bundle_root(platform: str) -> Path:
    if platform == "darwin":
        p = ROOT / "dist" / "tools.app"
        if p.is_dir():
            return p
        raise FileNotFoundError(f"Missing {p} (run PyInstaller on macOS first).")
    # Windows / Linux onedir
    p = ROOT / "dist" / "tools"
    if p.is_dir():
        return p
    raise FileNotFoundError(f"Missing {p} (run PyInstaller first).")


def _iter_files(root: Path) -> list[Path]:
    return [p for p in root.rglob("*") if p.is_file()]


def _fmt_mb(n: int) -> str:
    if n <= 0:
        return "0"
    mb = n / (1024 * 1024)
    if mb < 10:
        return f"{mb:.1f}"
    return f"{mb:.0f}"


def _write_inno_inc(out_dir: Path, sizes: dict[str, int], inc_path: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    total = sum(sizes[c] for c in _COMPONENT_ORDER)
    lines = [
        "; Auto-generated by scripts/stage_installer_components.py — do not edit by hand.",
        f'#define SizeRuntimeMB "{_fmt_mb(sizes["runtime"])}"',
        f'#define SizePdfMB "{_fmt_mb(sizes["pdf"])}"',
        f'#define SizePhotoMB "{_fmt_mb(sizes["photo"])}"',
        f'#define SizeMeetingMB "{_fmt_mb(sizes["meeting"])}"',
        f'#define SizeTotalMB "{_fmt_mb(total)}"',
        "",
    ]
    inc_path.write_text("\n".join(lines), encoding="utf-8")

    meta = {
        "runtime_bytes": sizes["runtime"],
        "pdf_bytes": sizes["pdf"],
        "photo_bytes": sizes["photo"],
        "meeting_bytes": sizes["meeting"],
        "total_bytes": total,
        "runtime_mb": float(sizes["runtime"]) / (1024 * 1024),
        "pdf_mb": float(sizes["pdf"]) / (1024 * 1024),
        "photo_mb": float(sizes["photo"]) / (1024 * 1024),
        "meeting_mb": float(sizes["meeting"]) / (1024 * 1024),
    }
    (out_dir / "component_sizes.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")


def _write_mac_distribution_xml(out_base: Path, sizes: dict[str, int], version: str) -> None:
    """Minimal installer-gui-script for productbuild (optional sub-packages)."""
    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="2">
    <title>tools</title>
    <options customize="always" require-scripts="false"/>
    <choices-outline>
        <line choice="runtime"/>
        <line choice="pdf"/>
        <line choice="photo"/>
        <line choice="meeting"/>
    </choices-outline>
    <choice id="runtime" visible="false" enabled="false" selected="true" title="Runtime"
        description="Application shell and shared libraries (about {_fmt_mb(sizes['runtime'])} MB unpacked).">
        <pkg-ref id="com.tools.pkg.runtime"/>
    </choice>
    <choice id="pdf" title="PDF / 水印与导出图片" start_selected="true"
        description="PyMuPDF text watermark and page raster export (about {_fmt_mb(sizes['pdf'])} MB unpacked).">
        <pkg-ref id="com.tools.pkg.pdf"/>
    </choice>
    <choice id="photo" title="Photo / 照片换底" start_selected="true"
        description="rembg + onnx (about {_fmt_mb(sizes['photo'])} MB unpacked).">
        <pkg-ref id="com.tools.pkg.photo"/>
    </choice>
    <choice id="meeting" title="Meeting / 会议纪要" start_selected="true"
        description="Microphone + Vosk local ASR (about {_fmt_mb(sizes['meeting'])} MB unpacked).">
        <pkg-ref id="com.tools.pkg.meeting"/>
    </choice>
    <pkg-ref id="com.tools.pkg.runtime" version="{version}" auth="Root">#runtime.pkg</pkg-ref>
    <pkg-ref id="com.tools.pkg.pdf" version="{version}" auth="Root">#pdf.pkg</pkg-ref>
    <pkg-ref id="com.tools.pkg.photo" version="{version}" auth="Root">#photo.pkg</pkg-ref>
    <pkg-ref id="com.tools.pkg.meeting" version="{version}" auth="Root">#meeting.pkg</pkg-ref>
</installer-gui-script>
"""
    (out_base / "distribution.xml").write_text(xml, encoding="utf-8")


def stage(platform: str) -> int:
    bundle = _bundle_root(platform)
    if platform == "darwin":
        out_base = ROOT / "dist" / "installer" / "mac"
    else:
        out_base = ROOT / "dist" / "installer" / "win"

    for name in _COMPONENT_ORDER:
        d = out_base / name
        if d.is_dir():
            shutil.rmtree(d)
        d.mkdir(parents=True, exist_ok=True)

    assignments: dict[str, list[str]] = defaultdict(list)
    size_by: dict[str, int] = defaultdict(int)

    for src in _iter_files(bundle):
        rel = _norm_rel(src, bundle)
        comp = classify_component(rel)
        assignments[comp].append(rel)
        size_by[comp] += src.stat().st_size

        dest = out_base / comp / src.relative_to(bundle)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)

    # sanity: every file assigned exactly once; union covers bundle
    all_rel_lower = {_norm_rel(p, bundle) for p in _iter_files(bundle)}
    union: set[str] = set()
    for c in _COMPONENT_ORDER:
        for r in assignments[c]:
            if r in union:
                print(f"duplicate assign: {r}", file=sys.stderr)
                return 1
            union.add(r)
    if union != all_rel_lower:
        print(
            f"partition mismatch missing={len(all_rel_lower - union)} extra={len(union - all_rel_lower)}",
            file=sys.stderr,
        )
        return 1

    full_sizes = {c: size_by.get(c, 0) for c in _COMPONENT_ORDER}

    for c in _COMPONENT_ORDER:
        comp_dir = out_base / c
        has_file = any(p.is_file() for p in comp_dir.rglob("*"))
        if c == "runtime" and not has_file:
            print("runtime staging has no files", file=sys.stderr)
            return 1
        if not has_file:
            (comp_dir / ".tools_component_placeholder").write_bytes(b"")

    out_base.mkdir(parents=True, exist_ok=True)
    _write_inno_inc(out_base, full_sizes, out_base / "component_sizes.inc")

    if platform == "darwin":
        ver = os.environ.get("TOOLS_PKG_VERSION", "0.0.0").lstrip("v").split("+")[0] or "0.0.0"
        _write_mac_distribution_xml(out_base, full_sizes, ver)

    print(f"Staged installer components under {out_base}")
    for c in _COMPONENT_ORDER:
        print(f"  {c}: {len(assignments[c])} files, ~{_fmt_mb(full_sizes[c])} MB")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--platform",
        default=sys.platform,
        help="darwin | win32 | linux (default: current)",
    )
    args = ap.parse_args()
    plat = args.platform
    if plat.startswith("linux"):
        plat = "linux"
    elif plat == "win32":
        plat = "win32"
    elif plat == "darwin":
        plat = "darwin"
    else:
        print(f"Unsupported platform: {args.platform}", file=sys.stderr)
        return 1
    try:
        return stage(plat)
    except FileNotFoundError as e:
        print(str(e), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
